#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow to listen on port 80
sudo ufw 'Nginx HTTP'

# Add page to return hello world when querying Nginx at its root / with a GET request (requesting a page) using curl
echo "Hello World!" | sudo tee /var/html/index.html

# restart nginx to load changes
sudo nginx restart
