#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow to listen on port 80
sudo ufw allow 'Nginx HTTP'


# Allow ssh
sudo ufw allow 'OpenSSH'


# Activate firewall and acknowledge the changes I made
echo y | sudo ufw enable


# Add page to return hello world when querying Nginx at its root / with a GET
# request (requesting a page) using curl
echo "Hello World!" | sudo tee /var/www/html/index.html


# configure server to have a custom 404 page containing the following string
# Ceci n'est pas une page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
regexp_for_replacement1="listen 80 default_server;"
replacement1="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/$regexp_for_replacement1/$replacement1/" /etc/nginx/sites-enabled/default


# restart nginx to load changes
sudo service nginx restart
