#!/usr/bin/env bash
# Create custom header for HTTP response

sed -i "/server_name _;/a\	add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default


# Restart nginx
sudo service nginx restart
